#ifndef CONST_H_
#define CONST_H_

#define OK 0
#define ERR_INVALID_KEY 100
#define ERR_DUPLICATE_KEY 101
#define ERR_KEY_NOT_FOUND 102
#define ERR_OUT_OF_MEMORY 103

#define ERR_QUEUE_EMPTY 200
#define ERR_QUEUE_FULL 201

#define ERR_OUT_OF_BOUNDS 300

#endif
